[build-system]
requires = ["setuptools>=66.1"]
build-backend = "setuptools.build_meta"

[project]
name = "codecheck"
version = "1"

[tool.setuptools.packages.find]
where = ["."]
include = ["codecheck*"]

[tool.setuptools.package-dir]
"" = "."
